# Generated by Django 4.0.4 on 2022-08-27 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imobile', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Options',
            new_name='Option',
        ),
    ]
