# Generated by Django 4.0.4 on 2022-08-27 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imobile', '0002_rename_options_option'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adress',
            options={'verbose_name_plural': 'Adresses'},
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name_plural': 'Features'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name_plural': 'Options'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'Persons'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name_plural': 'Sales'},
        ),
        migrations.RemoveField(
            model_name='property',
            name='features',
        ),
        migrations.AddField(
            model_name='sale',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='property', to='imobile.property'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PropertyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='imobile.feature')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='imobile.property')),
            ],
        ),
    ]
