# Generated by Django 4.0.4 on 2022-08-27 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imobile', '0003_alter_adress_options_alter_feature_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Option',
        ),
    ]
