# Generated by Django 4.0.4 on 2022-08-27 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imobile', '0004_delete_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='address',
        ),
        migrations.AddField(
            model_name='adress',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='imobile.property'),
            preserve_default=False,
        ),
    ]
